#!/usr/bin/env python3


MAX_LINE_LENGTH = 80

INDENT = ' ' * 6
HALF_INDENT = ' ' * 3


#### TODO: MAKE MORE GENERAL LATER
## DO NOT GET DISTRACTED RN AND WASTE TIME <3
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SEPARATOR_DOT = '.' * MAX_LINE_LENGTH
SEPARATOR_DASH = '-' * MAX_LINE_LENGTH
SEPARATOR_EQ = '=' * MAX_LINE_LENGTH
SEPARATOR_STAR = '*' * MAX_LINE_LENGTH
SEPARATOR_TILDE = '~' * MAX_LINE_LENGTH
SEPARATOR_WAVY = '〰'* MAX_LINE_LENGTH




#NODODY IS USING THIS ONE RNL:
#MINI_SEP_DOTS = center_by_padding('. '*12, MAX_LINE_LENGTH)